import type { NextPage } from 'next'
import Head from 'next/head'
import { ColorModeScript } from '@chakra-ui/react'
import Header from '../components/Navigation/Navigation'
import Hero from '../components/Hero'
import styles from '../styles/Home.module.css'
import theme from '../styles/theme';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Do Groc</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        {/* <Header></Header> */}
        <Hero></Hero>
      </body>
    </div>
  )
}

export default Home
